services:

  fiap-clientes-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - fiap-video-db-mysql
      - localstack
    ports:
      - 3000:3000
    environment:
      # Database 
      - DATABASE_HOST=fiap-video-db-mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=fiap
      - DATABASE_PASSWORD=fiap
      - DATABASE_DATABASE=fiap
      # PATH Files
      - PATH_PROCESSAR=/arquivos/processar/
      - PATH_DOWNLOAD=/arquivos/processados/
      # AWS SQS e SES Configs
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test-key
      - AWS_SECRET_ACCESS_KEY=test-key
      # AWS_SESSION_TOKEN=TOKEN-AWS-ACADEMY
      - AWS_SQS_ENDPOINT=http://localstack:4566 #PRODUÇÃO deve ser null
      - AWS_SES_FROM_EMAIL=sender@example.com # SES Notificações por email
      - AWS_COGNITO_USER_POOL_ID=us-east-1_XXXXXX
      - AWS_COGNITO_CLIENT_ID=12345abcdxyz
      - AWS_COGNITO_PERMIT_ALL=true
      # SQS filas
      - QUEUE_PROCESSAR=http://localstack:4566/000000000000/processar
      - QUEUE_PROCESSADOS=http://localstack:4566/000000000000/processados
    volumes:
      - /home/jackson/arquivos:/arquivos
  
  fiap-video-processamento:
    build:
      context: ../fiap-video-processamento/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PATH_PROCESSAR=/arquivos/processar/
      - PATH_PROCESSADOS=/arquivos/processados/
      - QUEUE_PROCESSADOS=http://localstack:4566/000000000000/processados
      - QUEUE_PROCESSAR=http://localstack:4566/000000000000/processar
      - QUARKUS_SQS_ENDPOINT_OVERRIDE=http://localstack:4566
      - QUARKUS_SQS_AWS_CREDENTIALS_TYPE=static
    volumes:
      - /home/jackson/arquivos:/arquivos

  # LocalStack para simular SQS, SES local e cognito
  # OBS: leia o README.md para executar os comandos necessários.
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,ses
      - AWS_DEFAULT_REGION=us-east-1

  fiap-video-db-mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql_data_fiap_video:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fiap
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap

volumes:
  mysql_data_fiap_video: {}
