apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: fiap-video
  name: fiap-video-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
