apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: fiap-video
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:latest
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: "ses" 
            - name: EDGE_PORT
              value: "4566"
            - name: DEFAULT_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "test"
          volumeMounts:
            - mountPath: /tmp/localstack
              name: localstack-data
      volumes:
        - name: localstack-data
          emptyDir: {}

apiVersion: v1
kind: Service
metadata:
  namespace: fiap-video
  name: localstack
spec:
  selector:
    app: localstack
  ports:
    - protocol: TCP
      port: 4566
      targetPort: 4566
  type: ClusterIP
