apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: fiap-video
  name: fiap-video-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/fiap-video-pv
